---
output:
  BiocStyle::html_document
---


```{r setup, cache=FALSE, echo=FALSE, results='hide', message=FALSE}
library(knitr)
library(SummarizedExperiment)
library(edgeR)

opts_chunk$set(cache=TRUE,
               cache.path="cache/file2",
               cache.extra=R.version.string,
               autodep=TRUE,
               fig.align="center",
               comment="")

se.filt <- readRDS(file.path("results", "paired_se.filt.rds"))
dge.filt <- readRDS(file.path("results", "paired_dge.filt.rds"))
```


We now proceed with limma analysis. We could use limma-voom or limma-trend. We could even comapre them if we had a gold standard. With a lack of gold standard to compare, we will use limma-voom, because the library sample size is ununiform.


```{r}
library(sva)

mod <- model.matrix(~se.filt$type, data = colData(se.filt))
mod0 <- model.matrix(~1, data = colData(se.filt))

sv <- sva(assays(se.filt)$logCPM, mod = mod, mod0 = mod0)

mod <- cbind(mod, sv$sv)
colnames(mod) <- c(colnames(mod)[1:2], paste0("SV", 1:sv$n))

table(table(se.filt$anatomic_organ_subdivision))

library(statmod)
corfit <- duplicateCorrelation(assays(se.filt)$logCPM, mod, block = se.filt$anatomic_organ_subdivision)
corfit$consensus

v <- voom(dge.filt, mod, plot=TRUE)

fit <- lmFit(v, mod)
fit <- eBayes(fit)

FDRcutoff <- 0.1
res <- decideTests(fit, p.value = FDRcutoff)
summary(res)

genesmd <- data.frame(chr = as.character(seqnames(rowRanges(se.filt))), symbol = rowData(se.filt)[, 1], stringsAsFactors = FALSE)

fit$genes <- genesmd

#table of results
tt <- topTable(fit, coef = 2, n = Inf)
head(tt)

#by chromosome
sort(table(tt$chr[tt$adj.P.Val < FDRcutoff]), decreasing = TRUE)
```

#plot p-values

```{r}
par(mfrow = c(1, 2), mar = c(4, 5, 2, 2))
hist(tt$P.Value, xlab = "Raw P-values", main = "", las = 1)
qqt(fit$t[, 2], df = fit$df.prior + fit$df.residual, main = "", pch = ".", cex = 3)
abline(0, 1, lwd = 2)
```


## Session information

```{r, message=FALSE}
sessionInfo()
```