---
output:
  BiocStyle::html_document
---

```{r setup, cache=FALSE, echo=FALSE, results='hide', message=FALSE}
library(knitr)

opts_chunk$set(cache=TRUE,
               cache.path="cache/DC",
               cache.extra=R.version.string,
               autodep=TRUE,
               fig.align="center",
               comment="")
```

# Import Data

```{r, message=FALSE}
library(SummarizedExperiment)

se <- readRDS(file.path("rawCounts", "seLUSC.rds"))
se
```

# Extract paired

```{r}
normal <- data.frame(colData(se)[colData(se)$type == 'normal',])$bcr_patient_barcode
tumor <- data.frame(colData(se)[colData(se)$type == 'tumor',])$bcr_patient_barcode


common_bcr_patient_barcode <- normal[normal %in% tumor]

length(common_bcr_patient_barcode)
# 47 patients that are paired


paired_seLUSC <- se[,colData(se)$bcr_patient_barcode %in% common_bcr_patient_barcode]

paired_seLUSC$bcr_patient_barcode <- droplevels(paired_seLUSC$bcr_patient_barcode)

saveRDS(paired_seLUSC, file.path("results", "paired_seLUSC.rds"))
```


